# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('tiles', 'tiles'),
        ('click.wav', '.'),
    ],
    hiddenimports=[
        'pygame',
        'pygame.mixer',
        'pygame.font',
        'pygame.image',
        'pygame.display',
        'pygame.event',
        'pygame.key',
        'pygame.mouse',
        'pygame.time',
        'pygame.transform',
        'pygame.draw',
        'pygame.surface',
        'pygame.rect',
        'pygame.gfxdraw',
        'pygame.locals',
        'pygame.constants',
        'pygame.version',
        'pygame.sndarray',
        'pygame.surfarray',
        'pygame.pixelarray',
        'pygame.math',
        'pygame.sprite',
        'pygame.mask',
        'pygame.freetype',
        'pygame.scrap',
        'pygame.cursors',
        'pygame.joystick',
        'pygame.color',
        'pygame.colordict',
        'pygame.bufferproxy',
        'pygame.threads',
        'pygame.rwobject',
        'pygame.pkgdata',
        'pygame._sdl2',
        'pygame._sdl2.audio',
        'pygame._sdl2.controller',
        'pygame._sdl2.mixer',
        'pygame._sdl2.video',
        'pygame.examples',
        'pygame.tests',
        'random',
        'copy',
        'math',
        'json',
        'os',
        'sys',
        'time',
        'collections',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='Korean_Mahjong',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

# Create Mac app bundle
app = BUNDLE(
    exe,
    name='Korean_Mahjong.app',
    icon=None,
    bundle_identifier='com.mahjong.korean',
    info_plist={
        'CFBundleName': 'Korean Mahjong',
        'CFBundleDisplayName': 'Korean Mahjong',
        'CFBundleVersion': '1.0.0',
        'CFBundleShortVersionString': '1.0.0',
        'NSHighResolutionCapable': True,
    },
) 